/**
 * Extracts the issue number encoded in a branch name generated by
 * {@link generateBranchName} (`${type}/${issue_id}-${slug}`, or any
 * pattern with `${issue_id}` in it) — the first run of digits in the
 * branch name. Branch types and slugs are never purely numeric, so this
 * is unambiguous for branches this extension created; branches that
 * don't encode an issue number (`main`, `feature/foo`) correctly yield
 * `null`.
 */
export function extractIssueNumberFromBranch(branchName: string): number | null {
  const match = branchName.match(/\d+/);
  if (!match) {
    return null;
  }
  return Number(match[0]);
}
